// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiZuS1tOiCgL6RFgE-NlJkWf8tIrnk0_o',
    appId: '1:109761333004:web:a05ec6b3ff4135e53feb29',
    messagingSenderId: '109761333004',
    projectId: 'tradingapp-36a3b',
    authDomain: 'tradingapp-36a3b.firebaseapp.com',
    storageBucket: 'tradingapp-36a3b.appspot.com',
    measurementId: 'G-5NW17GXMSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7gMTO_G91-EpY8UwNtGWRtJmQ60OAl3A',
    appId: '1:109761333004:android:1610e8a2fa15720f3feb29',
    messagingSenderId: '109761333004',
    projectId: 'tradingapp-36a3b',
    storageBucket: 'tradingapp-36a3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMTSAOSfRHFcvn6EAzRBd3_67bY9Idiws',
    appId: '1:109761333004:ios:b56fa3bbc61e8fe93feb29',
    messagingSenderId: '109761333004',
    projectId: 'tradingapp-36a3b',
    storageBucket: 'tradingapp-36a3b.appspot.com',
    iosBundleId: 'com.example.tradingApp',
  );
}
